### ISSUE TITLE
You are currently using minified code outside of NODE_ENV === "production". 

### ISSUE THREAD

**Issue by OrzX** [reduxjs/redux-starter-kit#68] opened 2019-01-04 17:04 UTC
When I use redux-starter-kit with webpack in production mode, keep telling me this:
`This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.`

I didn't find any file names like "*.min.js" under /node_modules/redux-starter-kit/dist/

**Comment by markerikson** [comment] 2019-01-04 17:11
Hmm.  It's possible we have our lib build settings wrong.

Can you create a small project that reproduces the issue?

**Comment by OrzX** [comment] 2019-01-04 17:50
```
$ create-react-app hello-redux
$ cd hello-redux
$ npm install --save redux-starter-kit
```

then add the code blew in /src/index.js
```js
import { getDefaultMiddleware } from 'redux-starter-kit';
// make sure the lib is imported.
const defaultMiddleware = getDefaultMiddleware();
```

```
$ npm run build
```

No we can see the warning message:
```
$ npm install -g serve
$ serve -s build
```

open `http://localhost:5000/`, the warning message should be displayed in the console output

**Comment by markerikson** [comment] 2019-01-11 19:35
Hmm.  Looking at the sourcemap, it kinda seems like it's maybe using the UMD build instead of the CommonJS or ESM builds.

**Comment by markerikson** [comment] 2019-01-11 19:42
Aha.  This look like it's sort of a dupe of #55 .

**Comment by markerikson** [comment] 2019-01-11 20:07
This should be resolved in https://github.com/reduxjs/redux-starter-kit/releases/tag/v0.3.2 .

**Closed by markerikson** 2019-01-11 20:07 UTC
